# Generated by Django 3.0.6 on 2020-10-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201015_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedProducts',
            new_name='OrderedProduct',
        ),
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
