# Generated by Django 3.0.6 on 2020-10-17 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201016_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
