# Generated by Django 3.0.6 on 2020-10-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefreview',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefreview_set', to='store.Chef'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreview_set', to='store.Product'),
        ),
    ]
