# Generated by Django 3.0.6 on 2020-10-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productreview_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.AddField(
            model_name='productreview',
            name='customer',
            field=models.ManyToManyField(to='store.Customer'),
        ),
    ]
