# Generated by Django 3.0.6 on 2020-10-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201023_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.AddField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=models.SET('Anonymous User'), related_name='customerreview_set', to='store.Customer'),
            preserve_default=False,
        ),
    ]
