# Generated by Django 3.0.6 on 2020-10-25 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201023_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
