# Generated by Django 3.0.6 on 2020-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='images/user'),
        ),
    ]
