# Generated by Django 3.1.2 on 2020-11-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201104_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
