# Generated by Django 3.1.2 on 2020-11-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
