# Generated by Django 3.1.2 on 2020-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20201211_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET('Anonymous User'), related_name='customerreview_set', to='store.customer'),
        ),
    ]
