# Generated by Django 3.1.2 on 2020-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20201211_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
