# Generated by Django 3.1.2 on 2020-12-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_delivary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivary',
            new_name='delivery',
        ),
    ]
