# Generated by Django 3.1.2 on 2020-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
