# Generated by Django 3.1.2 on 2020-12-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderedproduct_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
