# Generated by Django 3.1.2 on 2020-12-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20201225_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.order'),
        ),
    ]
