# Generated by Django 3.1.2 on 2020-12-25 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20201225_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='offers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
