# Generated by Django 3.1.2 on 2020-12-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_orderedproduct_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='offers',
            new_name='offer',
        ),
    ]
