# Generated by Django 3.1.2 on 2020-12-31 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20201231_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
