# Generated by Django 3.1.2 on 2021-01-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20210102_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='review',
        ),
        migrations.AddField(
            model_name='chefreview',
            name='review',
            field=models.TextField(default='Chef review default'),
            preserve_default=False,
        ),
    ]
