# Generated by Django 3.1.2 on 2021-01-04 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20210104_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_set', to='store.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 14, 33, 47, 577674)),
        ),
    ]
