# Generated by Django 3.1.5 on 2021-01-30 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20210130_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayherePaymentDetails',
            new_name='PayherePaymentDetail',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 14, 50, 21, 740158)),
        ),
    ]
