# Generated by Django 3.1.5 on 2021-02-05 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_auto_20210205_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 12, 52, 3, 678524)),
        ),
        migrations.AlterField(
            model_name='payherepaymentdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payherepayment_set', to='store.order'),
        ),
    ]
