# Generated by Django 3.1.5 on 2021-02-05 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_auto_20210205_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 13, 6, 27, 228499)),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('payhere', 'Payhere'), ('cashondelivery', 'Cash on delivery')], max_length=50),
        ),
    ]
