# Generated by Django 3.1.2 on 2021-02-08 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_auto_20210208_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 20, 2, 13, 147938)),
        ),
        migrations.AlterField(
            model_name='payherepaymentdetail',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
