# Generated by Django 3.1.2 on 2021-02-08 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_auto_20210208_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 20, 37, 52, 912859)),
        ),
        migrations.AlterField(
            model_name='payherepaymentdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payherepayment_set', to='store.order'),
        ),
    ]
