# Generated by Django 3.1.2 on 2021-02-08 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_auto_20210208_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 20, 39, 29, 82138)),
        ),
    ]
