# Generated by Django 3.1.2 on 2021-02-11 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_auto_20210211_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefreview',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='chefreview',
            name='customer',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 13, 56, 54, 173567)),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
        migrations.DeleteModel(
            name='ChefReview',
        ),
    ]
