# Generated by Django 3.1.2 on 2021-02-12 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_auto_20210211_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 20, 34, 59, 284281)),
        ),
    ]
